### ISSUE TITLE
Bug in close functionality

### ISSUE THREAD

**Issue by ar-g** [alex-townsend/SwipeOpenItemTouchHelper#19]
There is a bit strange behavior:
1. User swipes
2. Click on button which will delete item from RecyclerView
3. NotifyDataSetChanges instead of notifyItemRemoved(adapterPosition)
4. Swipe stay opened on next raw.

I tried to make some changes in the library but didn't get it to work yet. Any suggestions?

**Comment by alex-townsend** [comment]
This happens because notifyDataSetChanged() does not tell you what positions have changed, rather that the entire dataset has change. I guess the best functionality here would be to remove all the opened positions since we have no way on knowing if any views were removed.

I'll get this changed sometime this week -- until then I would recommend using notifiyItemRemoved() if at all possible (this is the recommended usage of a RecyclerView)

**Comment by ar-g** [comment]
@alex-townsend  I know, but db which I bind to hasn't such functionality. Yep, this works

```
 @Override public void onChanged() {
          super.onChanged();
          openedPositions.clear();
        }
```
