### ISSUE TITLE
How to use onSwiped method

### ISSUE THREAD

**Issue by josmanperez** [alex-townsend/SwipeOpenItemTouchHelper#38]
Hello!,

First of all thank you for this fantastic library, it helps a lot when trying to accomplish swipes views on a recycler view 👍 .

I have a scenario when I don't want to use a click listener on a button for launching an action, i.e, when a user swipes to the left side I show a button, but what I want to do if launch that action after you swiped complete on that side. 

I've managed to do all the swipe behaviour nice, if you swipe to the middle of the row it automatically swipes complete, but now I want to use the "onSwiped" method to fire an action but I can't figure out the best way to do it.

There is a nice comment **// do not use** so I was wondering how I can achieve the desire behaviour.

Thank you so much :)

**Comment by alex-townsend** [comment]
There's a comment to not use that since the library does not detect a full swipe of the ViewHolder in the RecyclerView like the ItemTouchHelper does (the library that this one was adapted from). If you're looking for full swipe detection/behavior for a ViewHolder, it may be a better option to look into the ItemTouchHelper (https://developer.android.com/reference/android/support/v7/widget/helper/ItemTouchHelper.html)

**Comment by josmanperez** [comment]
Thank you for your answer Alex :). I managed to adapt your code to detect when the view is going to be full swiped... its not perfect tho because the action that's supposed to be fired after the swiped has been completed, gets fire a few milliseconds before. 

The thing is that I was looking forward to implement this option on your library because I use everything else and the truth is the library is fantastic because it leverage you of the hard work, I think I'll let this behaviour for now instead of going with the google library and implement all the other work just for this.

Thank you again Alex

**Comment by alex-townsend** [comment]
Closing.
